#!/usr/bin/env bash
# Shared helpers for bench/bin/run-speed-tests
# shellcheck disable=SC2034

set -euo pipefail

BENCH_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UMBRELLA_ROOT="$(cd "${BENCH_ROOT}/.." && pwd)"
SAMPLE_APP="${SAMPLE_APP:-${UMBRELLA_ROOT}/ubuntu-mise/sample_app}"
RESULTS_DIR="${RESULTS_DIR:-${BENCH_ROOT}/results}"
RUN_ID="${RUN_ID:-}"
HTTP_TIMEOUT_S="${HTTP_TIMEOUT_S:-600}"
HTTP_INTERVAL_S="${HTTP_INTERVAL_S:-1}"

# Dedicated names so we never touch daily :dev images / *-cache volumes.
IMG_PROD="${IMG_PROD:-sample_app:bench-prod}"
IMG_DEV="${IMG_DEV:-sample_app:bench-dev}"
CTR_PROD="${CTR_PROD:-sample_app-bench-prod}"
COMPOSE_DEV_PROJECT="${COMPOSE_DEV_PROJECT:-sample-app-bench-dev}"
PORT_PROD="${PORT_PROD:-18080}"
PORT_DEV="${PORT_DEV:-13000}"
PORT_UBUNTU="${PORT_UBUNTU:-13100}"
PORT_ALPINE="${PORT_ALPINE:-13200}"
PORT_ARCH="${PORT_ARCH:-13300}"

# Dummy secrets for production boot only (not a real deploy key).
BENCH_SECRET_KEY_BASE="${BENCH_SECRET_KEY_BASE:-bench_speed_test_secret_key_base_not_for_production_use_0123456789abcdef}"

log() { printf 'bench: %s\n' "$*" >&2; }
die() { log "error: $*"; exit 1; }

require_tools() {
  command -v docker >/dev/null 2>&1 || die "docker not on PATH"
  docker info >/dev/null 2>&1 || die "docker daemon not reachable"
  docker compose version >/dev/null 2>&1 || die "docker compose plugin required"
  command -v curl >/dev/null 2>&1 || die "curl required"
  command -v python3 >/dev/null 2>&1 || die "python3 required"
  [[ -d "${SAMPLE_APP}" ]] || die "SAMPLE_APP not a directory: ${SAMPLE_APP}"
  [[ -f "${SAMPLE_APP}/Dockerfile" ]] || die "missing ${SAMPLE_APP}/Dockerfile"
}

now_epoch() {
  # Fractional seconds when available.
  date +%s.%N 2>/dev/null || date +%s
}

elapsed_s() {
  # elapsed_s <start_epoch>
  local start="$1"
  python3 -c "import sys; print(f'{float(sys.argv[1]) - float(sys.argv[2]):.3f}')" "$(now_epoch)" "${start}"
}

# Wait until URL returns HTTP 2xx. Prints elapsed seconds since start to stdout.
# Usage: wait_http <url> <start_epoch> [timeout_s]
wait_http() {
  local url="$1" start="$2" timeout="${3:-${HTTP_TIMEOUT_S}}"
  local deadline status code
  deadline="$(python3 -c "print(float('${start}') + float('${timeout}'))")"
  while true; do
    code="$(curl -sS -o /dev/null -w '%{http_code}' --connect-timeout 2 --max-time 5 "${url}" 2>/dev/null || true)"
    [[ -z "${code}" || "${code}" == "000" ]] && code="000"
    if [[ "${code}" =~ ^2[0-9][0-9]$ ]]; then
      elapsed_s "${start}"
      return 0
    fi
    python3 -c "import sys; sys.exit(0 if float(sys.argv[1]) < float(sys.argv[2]) else 1)" "$(now_epoch)" "${deadline}" \
      || { log "timeout waiting for ${url} (last http=${code})"; return 1; }
    sleep "${HTTP_INTERVAL_S}"
  done
}

docker_rm_ctr() {
  local name="$1"
  docker rm -f "${name}" >/dev/null 2>&1 || true
}

docker_rmi() {
  local img="$1"
  docker rmi -f "${img}" >/dev/null 2>&1 || true
}

volume_rm() {
  local vol="$1"
  docker volume rm -f "${vol}" >/dev/null 2>&1 || true
}

volume_ensure() {
  local vol="$1"
  docker volume inspect "${vol}" >/dev/null 2>&1 || docker volume create "${vol}" >/dev/null
}

# Append one result document to the run YAML file (as a list item under results:).
# Args via env: RESULT_* vars
append_result_yaml() {
  local out="${RESULTS_DIR}/${RUN_ID}.yaml"
  mkdir -p "${RESULTS_DIR}"
  if [[ ! -f "${out}" ]]; then
    cat >"${out}" <<EOF
# Speed bench results — generated by bench/bin/run-speed-tests
run_id: "${RUN_ID}"
started_at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
host: "$(hostname 2>/dev/null || echo unknown)"
sample_app: "${SAMPLE_APP}"
http_timeout_s: ${HTTP_TIMEOUT_S}
results: []
EOF
  fi
  RESULT_FINISHED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  RESULT_YAML_PATH="${out}" \
  python3 <<'PY'
import os, pathlib, re

path = pathlib.Path(os.environ["RESULT_YAML_PATH"])
text = path.read_text()
# Build a YAML list item (2-space indent under results:)
keys = [
    "scenario", "phase", "ok", "error",
    "t_build_s", "t_up_s", "t_root_s", "t_total_s",
    "port", "base_url", "image", "cache_volume",
    "notes", "finished_at",
]
item = ["  -"]
for k in keys:
    envk = "RESULT_" + k.upper()
    v = os.environ.get(envk, "")
    if v == "":
        if k in ("t_build_s", "t_up_s", "t_root_s", "t_total_s"):
            item.append(f"    {k}: null")
        elif k == "ok":
            item.append(f"    {k}: false")
        else:
            item.append(f"    {k}: null")
        continue
    if k == "ok":
        item.append(f"    {k}: {'true' if v in ('1', 'true', 'True') else 'false'}")
    elif k.startswith("t_") and k.endswith("_s"):
        item.append(f"    {k}: {v}")
    elif k == "port":
        item.append(f"    {k}: {int(v)}")
    else:
        # escape quotes
        v = v.replace("\\", "\\\\").replace('"', '\\"')
        item.append(f'    {k}: "{v}"')
block = "\n".join(item) + "\n"
# Insert before end: replace "results: []" first time, else append after last result
if re.search(r"^results: \[\]\s*$", text, re.M):
    text = re.sub(r"^results: \[\]\s*$", "results:\n" + block.rstrip("\n"), text, count=1, flags=re.M)
else:
    if not text.endswith("\n"):
        text += "\n"
    text += block
path.write_text(text)
print(path)
PY
}

record_failure() {
  local scenario="$1" phase="$2" err="$3"
  RESULT_SCENARIO="${scenario}" \
  RESULT_PHASE="${phase}" \
  RESULT_OK="false" \
  RESULT_ERROR="${err}" \
  RESULT_T_BUILD_S="" \
  RESULT_T_UP_S="" \
  RESULT_T_ROOT_S="" \
  RESULT_T_TOTAL_S="" \
  RESULT_PORT="" \
  RESULT_BASE_URL="" \
  RESULT_IMAGE="" \
  RESULT_CACHE_VOLUME="" \
  RESULT_NOTES="" \
  append_result_yaml
}

record_success() {
  # Caller must set RESULT_SCENARIO / RESULT_PHASE / timings / etc. as env for this call.
  RESULT_OK=true RESULT_ERROR="" append_result_yaml
}
